### ISSUE TITLE
[FEATURE REQUEST] Allow disabling the '+' Prefix in individual style bonuses.

### ISSUE THREAD

**Issue by UntotenTheo** [eternalUnion/UltrakillStyleEditor#6]
# Description
hi eu
I think it'd be cool if we could disable the '+' Prefix for individual style bonuses via a toggle below 'Italic,' that way something like **'+PARRY'** appears as just **'PARRY'**.

# Extra
nothin else to add :p

**Comment by eternalUnion** [comment]
it is a little hard because all the styles are stored in a single line. removing the last style is basically finding the position of the last '+' and removing everything behind it. that is why '+' character cannot be used in style texts, and also why people experienced broken style texts when they used it in their custom styles in older versions

**Comment by UntotenTheo** [comment]
ah, i see
in that case might not be worth the trouble
thanks for the reply

**Comment by UntotenTheo** [comment]
closing issue
